### ISSUE TITLE
Chat scrollbar invisible

### ISSUE THREAD

**Issue by REVENGE977** [nanoqoi/vencord-theme#13]
![image](https://github.com/Synqat/vencord-theme/assets/32039975/12587304-944c-421f-9ba3-43e874dd2127)

The text channel scrollbar thumb color is identical to the scrollbar background color, making it difficult to scroll by grabbing the scrollbar with the mouse pointer.

**Comment by abirhasan132** [comment]
#13

**Comment by SkyExploreWasTaken** [comment]
Yeah it happens to me too idk why.
